import { MILLISECONDS_PER_MINUTE } from '../../shared/datetime/index.ts';

export const ORDERBOOK_LEVEL_COUNT = 100;
export const ORDERBOOK_ASK_ORDER_ID_OFFSET = 500_000n;
export const ORDERBOOK_ORDER_ID_TIME_MULTIPLIER = 1_000_000n;
export const ORDERBOOK_ORDER_ID_LEVEL_MULTIPLIER = 100n;
export const ORDERBOOK_QUEUE_ID_LEVEL_MULTIPLIER = 1_000n;
export const ORDERBOOK_SNAPSHOT_INTERVAL_MS = 10 * MILLISECONDS_PER_MINUTE;
