name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build:
    name: test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Setup package manager and dependencies
        run: bash ./scripts/setup/.setup-ci.sh

      - name: Run checks
        run: pnpm run check

      - name: Run unit coverage
        run: pnpm run coverage

      - name: Build
        run: pnpm run build
